version: '2'
services:
  web:
    image: "dynamicflow/staticache:latest"
    ports:
      - "8080:8080/tcp"
    volumes:
      - storage-data:/var/lib/staticache
    environment:
      - STATICACHE_DB=mysql://root:statipass@mysql:3306/staticache
    depends_on:
      - db
    links:
      - db:mysql
    networks:
      - front-tier
      - back-tier

  db: 
    image: "mysql:5.7.13"
    ports:
      - 3306
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=statipass
      - MYSQL_DATABASE=staticache  
    networks:
      - back-tier

volumes:
  db-data:
    external:
      name: staticache-db-data
  storage-data:
    external:
      name: staticache-storage-data

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
